### PR TITLE
Processing events before and after other fixtures are teardown

### LINKED ISSUE #67: Processing test events happens in hookwrapper
So I was looking into why the exception in #65  is actually happening for me: It seems the test finishes *after* a module I'm monkeypatching is already un-monkeypatched:

```python
@pytest.fixture(autouse=True)
def mock_modules(monkeypatch, stubs):
    monkeypatch.setattr('qutebrowser.misc.guiprocess.message',
                        stubs.MessageModule())
```

I'm guessing this is because `pytest_runtest_teardown()` is decorated with `@pytest.mark.hookwrapper` - should it really be? I think it'd make more sense to run it before other fixtures are torn down.

### PR DESCRIPTION
**Pull request by nicoddemus**
Fixes #67

### CODE REVIEW

**Comment by The-Compiler** [comment]
I also pushed a test for #67 to your branch - ready to merge as far as I'm concerned!

**Comment by nicoddemus** [comment]
Thanks! I tried to create a test for it, but was not satisfied what I came up with. I will change the test you slightly later to use `single_shot` fixtures (I'm a bit traumatized about `QTimer.singleShot` :stuck_out_tongue_winking_eye:) and see if I test how to test that process events were also called after other fixtures were tear down., :smile:

**Comment by The-Compiler** [comment]
Let me know when the new test is ready - then I can test if it actually fails on master on my Ubuntu Trusty VM.

**Comment by nicoddemus** [comment]
Will do! :smile:

**Comment by nicoddemus** [comment]
Add the new test... it is a little complicated, but it covers that process events is called at the proper times. BTW, the test shows a situation where a new event might be queued during a fixture tear down, which could affect the next test. :wink:

Feel free to merge if it looks OK to you.

**Comment by The-Compiler** [comment]
Nice! Just merged it - thank you! I never went that low-level with Qt's event system, but it looks good to me :smile:

**Comment by The-Compiler** [comment]
By now I have several tests which fail on Windows but seem to be okay with this change - do you plan a release anytime soon? I'd appreciate it!

**Comment by nicoddemus** [comment]
I was planning on releasing **1.6.0** after merging #63, which I think I can work on this week and make a release until Friday at latest. Can you wait until then? :smile:

**Comment by The-Compiler** [comment]
Oh, I didn't expect you to merge this already - but sure, I can wait until then!

I'm unfortunately still busy with the next qutebrowser release, as there were some trouble with other tests on Windows and there was another bad bug found.

**Comment by nicoddemus** [comment]
1.6.0 is out. :smile:

**Pull request merged**
