### PR TITLE
Add wait argument to qtbot.assertNotEmitted

### PR DESCRIPTION
**Pull request by The-Compiler**
I swear this is the last one :see_no_evil: Take your time to review things though, I'm not in a hurry!

Needed this for some tests in qutebrowser recently, and it seems simple enough to add it.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Whoops, accidentally had a `;` at the end of the line in the docs :laughing:  That's what I get for writing JavaScript, C++ and Python on the same day!

**Comment by The-Compiler** [comment]
Thinking about this some more, I noticed a QEventLoop is spin up every time `assertNotEmitted` is used now (with the default `timeout=0`), which seems weird.

I've opted to just not spinning up an event loop with `qtbot.waitSignal(..., timeout=0)` at all, see the last commit - what do you think?

**Comment by nicoddemus** [comment]
> I've opted to just not spinning up an event loop with qtbot.waitSignal(..., timeout=0) at all, see the last commit - what do you think?

Seems reasonable, thanks!

**Comment by nicoddemus** [comment]
(and sorry for the delay!)

**Pull request merged**
