### PR TITLE
fixed bug #248

### LINKED ISSUE #248: typo in modeltest._on_rows_about_to_be_inserted
Hello,

just to mention that, in modeltest._on_rows_about_to_be_inserted,  the following line (549):

`last_data = self._model.data(last_index) if start - 1 > 0 else None`

should be:

`last_data = self._model.data(last_index) if start - 1 >= 0 else None`

since start can be equal to 1.

It is actually like this in the [qt5 source code](https://code.woboq.org/qt5/qtbase/src/testlib/qabstractitemmodeltester.cpp.html#_ZN31QAbstractItemModelTesterPrivate21rowsAboutToBeInsertedERK11QModelIndexii) (line 643):

`c.last = (start - 1 >= 0) ? model->index(start - 1, 0, parent).data() : QVariant();`

Thank you.

### PR DESCRIPTION
**Pull request by ext-jmmugnes**
Fix #248

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @ext-jmmugnes, thanks a lot for the PR.

@The-Compiler do you feel we should add a test for this, or is it fine to merge as is?

**Comment by bruchar1** [comment]
Any updates on this?

**Comment by nicoddemus** [comment]
Thanks for the ping, I'm going ahead with the merge given that @The-Compiler seems fine with this as is (https://github.com/pytest-dev/pytest-qt/issues/248#issuecomment-435318315). Either way we can always add a test later.

**Comment by nicoddemus** [comment]
Thanks @ext-jmmugnes for the PR!

I will make a release later today.

**Comment by nicoddemus** [comment]
Released `3.2.2`, thanks again!

**Pull request merged**
