### PR TITLE
Prepare release 2.4.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
cc @The-Compiler

**Comment by The-Compiler** [comment]
LGTM, but might want to adjust the length of the dashed line below it as well?

**Comment by nicoddemus** [comment]
Argh, definitely, thanks!

**Comment by The-Compiler** [comment]
Thanks for taking care of the release! However, looks like [something broke there](https://travis-ci.org/pytest-dev/pytest-qt/builds/383147244)?

**Comment by nicoddemus** [comment]
Yeah that's weird, it was [during `coveralls`](https://travis-ci.org/pytest-dev/pytest-qt/jobs/383147248#L1018):

```
$ coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Failure to submit data. Response [504]: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Coveralls :: Oops, something went wrong (500)</title>
```

Doesn't seem something to worry about (the release went out after all), but something to watch for in the future.

PS: I have a mind to try `codecov` sometime. I like the reports better and `coveralls` seems to have some hiccups on occasion.

**Pull request merged**
