### PR TITLE
Make wait* arguments kw-only

### LINKED ISSUE #366: Use kwonly arguments for wait*
While reading this I realized `waitSignal` (and friends) have this signature:

```python
def waitSignal(self, signal, timeout=5000, raising=None, check_params_cb=None):
```

While IMHO this would be better:

```python
def waitSignal(self, signal, *, timeout=5000, raising=None, check_params_cb=None):
```

(Of course this is an artifact from Python 2 support).

Don't want to pile this on for 4.0, just commenting to see what you think.

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest-qt/pull/363#discussion_r644240304_

### PR DESCRIPTION
**Pull request by The-Compiler**
Closes #366

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
Awesome, thanks!

**Comment by The-Compiler** [comment]
Thanks for all the reviews! :+1: 

What's left to do the release? Remove the UNRELEASED in the changelog and push a tag?

**Comment by nicoddemus** [comment]
Pretty much! 😁 

Also feel free to do the honours of announcing the new release on Twitter, given you did all the work on the new release. 🙇

**Comment by The-Compiler** [comment]
Done, release build is running: https://github.com/pytest-dev/pytest-qt/actions/runs/903331101 - fingers crossed that the PyPI deploy stuff still works after such a long time! :crossed_fingers: 

Took the freedom to push to master directly (f258f31954ce5dd932d574ca8182d3703127c500) given that the only thing left was the date and the CI already passed recently.

**Comment by nicoddemus** [comment]
Awesome!

**Pull request merged**
