### PR TITLE
Using Conda to install PyQt on travis

### LINKED ISSUE #35: Update travis build to test PyQt5
As suggested by @jdreaver, an alternative is trying to use conda for that:

* http://conda.pydata.org/docs/travis.html
* https://binstar.org/jdreaver/pyqt5

### PR DESCRIPTION
**Pull request by nicoddemus**
This fixes #35.

### CODE REVIEW

**Comment by nicoddemus** [comment]
@jdreaver, you might want to take a look at this. :smile:

**Comment by jdreaver** [comment]
I think there is an error in the Travis docs. It looks like they put the `xvfb` line into `before_install` instead of `before_script`. Maybe try changing `before_install` into `before_script`? I'll investigate more.

**Comment by jdreaver** [comment]
That sucks. I wish we could manually ssh into Travis to try commands... I'll do more research.

One more thing to try is simply `xvfb-run -s "-screen 0 1280x1024x24" coverage run --source=pytestqt setup.py test` in the "script" section, and delete the `before_script` section. I somewhere saw that `xvfb-run` might be installed on Travis machines. If this doesn't work, then I bet the arguments we have to `xvfb` are wrong.

**Comment by nicoddemus** [comment]
:pray: :smile:

**Comment by jdreaver** [comment]
If that doesn't work, we could also try:

```
before_script:
 - export XVFBARGS="-screen 0 1280x1024x24" 
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
```

Sorry for the ideas that don't work, I'm just throwing plausible things I find at you! :smile:

**Comment by jdreaver** [comment]
Hmm, it seems that now just the PyQt5 tests are failing. I wonder if there are other dependencies that are missing now...

I might have to test my `pyqt5` package on a headless Ubuntu 12.04 directly to see what's up.

**Comment by nicoddemus** [comment]
> Sorry for the ideas that don't work, I'm just throwing plausible things I find at you! :smile:

Please, your help is greatly appreciated! :smile:

**Comment by nicoddemus** [comment]
@jdreaver would you like me to add you as a collaborator here? You can then try the commands yourself if you want to investigate this further.

**Comment by jdreaver** [comment]
That would be great! I'll probably continue this within the next week. First I'll try this on an Ubuntu 12.04 box. I think there must be some graphics dependency missing, but who knows what it is.

**Comment by nicoddemus** [comment]
@jdreaver invited! 

Feel free to commit in this branch as much as you like, as I plan to clean it up anyway before merging it on `master`.

Thanks again for all the help! :smile:

**Pull request closed without merging**
