### PR TITLE
updated modeltester to allow QBrush as BackgroundColorRole

### PR DESCRIPTION
**Pull request by p0las**
pyQt5 takes QBrush as BackgroundColorRole and TextColorRole.

### CODE REVIEW

**Comment by nicoddemus** [comment]
2.2.1 published! Thanks @p0las! 😁

**Comment by The-Compiler** [comment]
I was in bed while all this happened, great work! 👍 

We should probably have a test for this though, no?

**Comment by p0las** [comment]
@The-Compiler I have been thinking the same. Fix without a failing test first is not a great one.

**Comment by nicoddemus** [comment]
Yep, completely missed that point for some reason. 😅 

@p0las would you like to work on this? I assume we just need a "model" which returns a `QBrush` for those roles.

**Comment by nicoddemus** [comment]
Created: #191

**Pull request merged**
