### PR TITLE
Reference TimeoutError and ScreenshotError via qtbot

### LINKED ISSUE #459: Difference between `pytestqt.exceptions.TimeoutError` and Python's `TimeoutError`
Python has a `TimeoutError` already: https://docs.python.org/3/library/exceptions.html#TimeoutError

What is the purpose of `pytestqt.exceptions.TimeoutError`, which is not derived from `TimeoutError`? It is very easy write a

```python
try:
  ...
except  TimeoutError:
  pass
```

that does not work as intended because one is missing `from pytestqt.exceptions import TimeoutError` (which by the way gives:
> Redefining built-in 'TimeoutError'

in `pylint`).

I think `pytestqt.exceptions.TimeoutError` could be removed or, if it should be kept for compatibility, it should derive from `TimeoutError`.

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #459

### CODE REVIEW

**Comment by nicoddemus** [comment]
cc @bersbersbers

**Review by The-Compiler — CHANGES_REQUESTED** [review]
Thanks! I think the initial doc snippet in `signals.rst` should be updated as well, and maybe references to those exceptions in our tests too?

**Comment by The-Compiler** [comment]
Sorry, I dropped the ball on this a bit - is it intended that 629c2cd6b23a65d4f3742c7520b98d80c77659dd includes changes to the pre-commit config?

**Review by The-Compiler — APPROVED** [review]
LGTM other than what I mention about the pre-commit config.

**Comment by nicoddemus** [comment]
Hmm good catch, should be separate, let me rebase.

**Comment by The-Compiler** [comment]
Looks like the pre-commit changes are still there? :thinking:

**Comment by nicoddemus** [comment]
Ahh they are, but they are in a separate commit. :+1: 

I don't think we need a separate PR for those changes, or do you prefer a separate PR?

**Review by The-Compiler — APPROVED** [review]

**Pull request merged**
