### PR TITLE
Use explicit try/finally to ensure loops quit when receiving a signal

### LINKED ISSUE #114: Hang when exception is raised in _quit_loop_by_signal
I haven't investigated that closely yet, thought I'd open an issue before I forget.

When raising an exception in `_quit_loop_by_signal`:

```diff
diff --git a/pytestqt/wait_signal.py b/pytestqt/wait_signal.py
index c32a76c..7efc019 100644
--- a/pytestqt/wait_signal.py
+++ b/pytestqt/wait_signal.py
@@ -111,6 +111,7 @@ class SignalBlocker(_AbstractSignalBlocker):
         """
         quits the event loop and marks that we finished because of a signal.
         """
+        raise Exception
         self.signal_triggered = True
         self._loop.quit()
         self._cleanup()
```

Then pytest-qt's tests seem to hang:

```
$ tox -e py35-pyqt5 -- tests/test_wait_signal.py -v 
[...]
test_wait_signal.py::test_signal_blocker_exception PASSED
test_wait_signal.py::test_signal_triggered[200-None-True-wait_function0-True] 
```

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #114

### CODE REVIEW

**Comment by The-Compiler** [comment]
LGTM!

**Comment by nicoddemus** [comment]
Also noticed that `MultiSignalBlocker was not disconnecting its signals... :scream:

**Comment by The-Compiler** [comment]
I think in https://github.com/pytest-dev/pytest-qt/pull/71#issuecomment-128038635 we discovered it wasn't actually needed with `MultiSignalBlocker` but didn't figure out why - so I guess let's just do it now that you implemented it :wink:

**Comment by nicoddemus** [comment]
Hmm oh yeah, we kinda just let it go at that. Oh well, I think now everything is working as it should. :smile:

**Pull request merged**
