### PR TITLE
Update modeltester to latest Qt sources

### PR DESCRIPTION
**Pull request by The-Compiler**
See #221

Last one for now :wink:

### CODE REVIEW

**Comment by The-Compiler** [comment]
I think I'll need some help with Qt 4 here. Looking at it, I don't think the type checks ever worked properly there, but our tests only tested wrong types and the `DisplayRole`, which happened to be added to the checked roles with the upstream Qt changes.

I'm not really sure what the right way to make this work is. I think before 41b83acae0db37eb1b073450f917e6db26154a1d the checks didn't make much sense at all, and c2403a02d38edd9664448fae07f3337d34d51836 seems to be needed for Python 2. But now I also see `QString` in the tests, so apparently the allowed types should be one of:

- `str` (Python 3)
- `unicode` (Python 2)
- `QString` (if available)

or something?

**Comment by nicoddemus** [comment]
You are right that it seems previously nothing was tested properly.  

PyQt4 originally (the `pyqt4` API) always returned native `QString` objects. The V2 API (`pyqt4v2`), introduced later, returns native Python types instead. So in Python 2 I assume those are always `str` objects in some who-knows-what encoding. At work we do something like `qstring.utf8().decode('utf-8')` to obtain a `unicode` object.

Well it is quite a pickle. I pushed some tweaks to that in de8702b, let's see how it fares.

**Comment by The-Compiler** [comment]
Oh, seems to look better now, thanks! Not sure if I should also add some more tests, but on the other hand I think the actual test coverage (i.e. "cases" of broken models we test) didn't really change much.

**Comment by nicoddemus** [comment]
I guess we can add the changelog entry later before the release. 👍

**Pull request merged**
